### ISSUE TITLE
buy, sell 페이지 구현

### ISSUE THREAD

**Issue by jsmoon2225** [KREAM-Team/KREAM#28]
## 📄작업 설명
- 구매, 판매 페이지 디자인과 select, insert 실행

## ☑️TO-DO
- [ ] 구매 ,판매 페이지 디자인
- [ ] 상품 select 후 화면에 표시
- [ ] 구매,판매 입찰 금액 DB에 insert
